---
- name: Call child playbooks for apache2
  hosts: all
  tasks:
    - name: Call playbooks for apache
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_apache_response.yml
...
