---
- name: Implementing tags
  hosts: all
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: 
        - tree_installation
        - always
    - name: Create a user
      user:
        name: Anusha
        password: intelliqit
      tags: 
        - user_creation
        - never
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...
